### ISSUE TITLE
Units cannot be damaged when 'stunned' with `PauseUnit ()`

### ISSUE THREAD

**Issue by RandomPickNewb** [nvs/gem#156]
While a creep is under the effect of the hold slate stun he will not take damage from the blood star.Didnt test with fire star/ancient slate stun.Final star upgrade works fine.
Managed to recreate the bug(god the rng was awful).
replay http://storage.entgaming.net/replay/view_replay.php?file=8099788.w3g (10:30 mins +)

**Comment by nvs** [comment]
Yes, please add the ENT link when it becomes available as that will be easier to reference. However, if you put the replay directly into a ZIP file you should be able to attach it directly to the issue. That would be preferred to external download sites. The only file types supported by attachments here are: PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, and ZIP.

Anyways, you're right. And this is definitely an issue that existed in the old versions of Gem as I've touched nothing related to this yet. Without testing or looking at the code I'm almost positive that it is related to use of the function `PauseUnit ()` to 'stun' units. Bryvx did a few changes through the versions to try to fix 'stun' behavior, and even though he claimed he fixed things #154 was brought to my attention.

But somehow a paused unit does not interact properly with either spell damage and/or a debuff of the likes provided by the Stars (not Fire Star, that does physical damage), the unupgraded damage of Uranium, some of the damage of Viper Slate, the AoE of Red Quartz Crystal, etc. If this is the case, then any source of 'stun' is bugged in a similar fashion.

**Comment by nvs** [comment]
This is an interesting bug, but is essentially blocked by #154.
