### ISSUE TITLE
All Opals start with their first-level aura

### ISSUE THREAD

**Issue by notwa** [nvs/gem#292]
In the latest development version (1.4.0-alpha), Opal towers that are built directly (not from combining lesser towers) only have the effectiveness of a Chipped Opal. I haven't tested downgrading towers. I believe this is a regression, as I haven't had it happen in version 1.3.3.

![wc3scrnshot_060717_075203_01 85](https://user-images.githubusercontent.com/1459466/27009287-ec7776a0-4e3e-11e7-8183-091251aaf842.jpg)

**Comment by nvs** [comment]
Definitely a regression. I find it a bit funny since I previously fixed a similar bug, albeit that was only related to downgrading. I expect some issues, given the amount of code I was rewriting.

**Comment by notwa** [comment]
Looks like it's working. Tested downgrades too.
