### ISSUE TITLE
One-hit Specials can fulfill incorrect recipe

### ISSUE THREAD

**Issue by notwa** [nvs/gem#294]
Regression in 1.4.0-alpha: the Combine Special spell is given every tower after placing 5 gems meeting a recipe — this is fine, 1.3.3 does this too. However, unlike 1.3.3, you get the special of whichever tower you use the spell on. This means you can get specials that you don't actually meet the requirements for.

The easiest way to see this (without cheating or debug stuff) is to keep placing the initial 5 gems at the start of the game. There's a chance you'll wind up with a one-hit Silver or Malachite, but you'll also be able to create the other special you *don't* meet the requirements for. Maybe even a Star Ruby on the first round!

I have save files if needed.

**Comment by nvs** [comment]
No save files are needed. This was pretty easy to duplicate, as you can comment out gem types in `src/gem/types.j` to limit what you are offered. For example:
```
function Gem_Type__Initialize takes nothing returns boolean
	set Gem_Type___ID = ID ()

	//set Gem_Type__AMETHYST = Gem_Type___Allocate ()
	set Gem_Type__AQUAMARINE = Gem_Type___Allocate ()
	//set Gem_Type__DIAMOND = Gem_Type___Allocate ()
	set Gem_Type__EMERALD = Gem_Type___Allocate ()
	set Gem_Type__OPAL = Gem_Type___Allocate ()
	set Gem_Type__RUBY = Gem_Type___Allocate ()
	//set Gem_Type__SAPPHIRE = Gem_Type___Allocate ()
	//set Gem_Type__TOPAZ = Gem_Type___Allocate ()

	return false
endfunction
```

Sure enough, I was able to make a Star Ruby even though I should have only had a Malachite.

Taking a quick look, I know exactly what happened. The rewrite of gem placement and selection was dragged out over about half a year for various reasons (mostly lack of time). My approach morphed multiple times, and it seems I wasn't as careful as I should have been in some parts (Opal auras being another example). Should be a quick fix.
