### ISSUE TITLE
i want to know something;

### ISSUE THREAD

**Issue by wdw753951** [nvs/gem#346]
Hello dear author,  I am a player from china ,though i am not a programer of jass ,but i write other language, i have read some of the trigger of the game from your code,for example the extra_chance and the palcement, i want to know the two triggers is whether written by you or writter by the orgin author,so i can write some thing in the map which is translate into chainese named 4.05pro, i want to try modify the extra-chance out of the game.
thank you

**Comment by nvs** [comment]
In Gem TD+, the code for extra chance and placement was written by me. For the most part, the only old code left (by Bryvx using the World Editor's GUI) is in [src/gem-3.1.j](https://github.com/nvs/gem/blob/develop/src/gem-3.1.j) (and some of what is in [src/gem-3.1](https://github.com/nvs/gem/blob/develop/src/gem-3.1)). Some of that has been modified by me as well, fixing bugs and integrating with the new stuff.

The easiest way to disable extra chance (in both Gem TD+ and the original Gem TD) would be to remove the abilities from the Gold Mine. The code and triggers would exist, but it should be impossible for players to use extra chance.

**Comment by nvs** [comment]
Closing as the question has been answered. If you need further details, don't hesitate to ask more.
