### ISSUE TITLE
Opal Aura Bug

### ISSUE THREAD

**Issue by ry1015** [nvs/gem#414]
I have 2 Great Opals and a Flawless Opal. All within range of each other.
The towers within the range only gets Opal Aura level 4. While one of the Great Opals and Flawless opal get level 6.

**Comment by nvs** [comment]
There is no replay available, so I can't be sure. However, it sounds like the same issue as in #3. Basically, the opal aura visually fluctuates. If you had kept the mouse over the buff icon, I bet it would change between the various levels.

In that other issue I did some basic testing (although, I need to do more). It seemed as though it was a visual bug only. That being said, it still annoys me. I will probably address this issue when I approach general aura improvements for the map.

I'll mark this as a duplicate for now. If you don't think it is, please do let me know.

**Comment by nvs** [comment]
Just wanted to mention I tested this again, and it is only a visual bug. The best Opal aura in range is always used.
