### ISSUE TITLE
Extra chance hotkey is not set beyond the first level

### ISSUE THREAD

**Issue by ScopeyNZ** [nvs/gem#528]
Once you've upgraded gem chance once, the hotkey for upgrading gem chance is gone.

I said I've been meaning to raise this so I finally did 😉

**Comment by nvs** [comment]
I believe this was was addressed in 1.6.11. Have you checked in that version yet?

**Comment by ScopeyNZ** [comment]
Ah, nope. Just checked the changelog. I'll double check shortly.

**Comment by nvs** [comment]
Not every small change gets listed in the changelog. I believe it was this commit: 8cb0f8027725bc391fc723cee671a957d0cb1fac

**Comment by ScopeyNZ** [comment]
Yep. It's fixed. Thanks

**Comment by nvs** [comment]
Great!
