### ISSUE TITLE
Error when git cloning repo with `--recurse-submodule`

### ISSUE THREAD

**Issue by kokimoribe** [nvs/gem#532]
Hello! Thanks for maintaining Gem TD. I was interested in reading through the codebase and decided to check out the repo with the following command (based from `README.md`):

```
git clone --recurse-submodule https://github.com/nvs/gem.git
```

The above command exits with a non-zero code with the following error message:

```
fatal: repository 'https://github.com/nvs/WurstStdlib2/' not found
fatal: clone of 'https://github.com/nvs/WurstStdlib2' into submodule path 
```

Based on the error message, I think`.gitmodules` may need to be updated?

https://github.com/nvs/gem/blob/master/.gitmodules#L5

Or, is this submodule intended to be a private fork of `wurstscript/WurstStdlib2`?

**Comment by nvs** [comment]
Hi. I think 558cb892926092263eb70b274b746dcd2ec6a108 should take care of the issue. The WurstStdlib2 is no longer utilized as a submodule. 

It should be noted that 1.6 is the last Gem TD+ that will use Jass. As of 1.7, the map will be Lua based. I just have not pushed any of that work to the repository yet.

**Comment by kokimoribe** [comment]
Right on. Thanks for linking the change. Going to go ahead and close this.

**Comment by nvs** [comment]
I also just pushed a change to the README of the 0.6 branch of Map, indicating the need of lua-stormlib 0.1.6.
